# bag
topic_lidar: /velodyne_packets 
topic_imu: /novatel/oem7/imu/data_raw 


LidarModel: "VLP_16_packet"
#vlp16_ring_case: 0

scan4map: 15.0
ndtResolution: 0.5 # 0.5 for indoor case and 1.0 for outdoor case
ndt_key_frame_downsample: 0.1
map_downsample_size: 0.25

knot_distance: 0.01

use_gui: false
# when segment_num = 1, 
# 当 segment_num = 1时，即用一段数据标定
segment_num: 1
selected_segment:
  - {start_time: 0, end_time: 243, path_bag: /root/catkin_oa_calib/src/OA-LICalib/data/my_bags/08_22_2024/1/vlp16icmspanhwsync.bag}
                                                                                                                                
# If you select false, it calculate initial rotations.
# If you know the approximate conversion between the sensors, set true.
plane_motion: false

# SPAN
gyro_weight: 2.8
accel_weight: 2.0
lidar_weight: 1.0



lock_accel_bias: false

opt_timeoffset: True
timeoffset_padding: 0.1

opt_lidar_intrinsic: true
opt_IMU_intrinsic: true

iteration_num: 50

# For CalibParamManager
extrinsic:

  Trans: [0.03, -0.15, -0.07]
  Trans_prior: [0.03, -0.15, -0.07]



  Rot: [1, 0, 0,
       0, 1, 0,
       0, 0, 1]

  # Trans: [0.3, 0.15, 0.05]

  # gt [1, 2, 5]deg
  # Rot: [  0.995588, -0.0871026,  0.0348995,
  #       0.0877492,    0.99599, -0.0174418,
  #     -0.0332403,  0.0204272,   0.999239]
